In [1]:
import numpy as np
import pandas as pd

In [2]:
#Loading data
df = pd.read_csv('messy_healthcare_dataset.csv')
df_cpy1 = df.copy()
df_cpy1

,Patient_ID,Name,Age,Gender,Appointment_Date,Doctor_Name,Department,Wait_Time(min),Diagnosis,Bill_Amount,Payment_Status,City
0,P1,Priya,22,M,31-05-2023,Dr. Sara,Orthopedic,44.0,NaN,NaN,UNPAID,Bangalore
1,P2,David,Unknown,NaN,19-09-2023,Dr. Sara,Cardiology,58.0,Diabetes,6634.84,paid,Bangalore
2,P3,Rahul,13,M,2023-01-20 0:00:00,Dr. John,Cardiology,NaN,NaN,NaN,UNPAID,Kolkata
3,P4,Priya,Unknown,NaN,2023/04/13,Dr. Priya,Neurology,5.0,Checkup,NaN,Unpaid,Bangalore
4,P5,John,NaN,Male,2023/05/28,Dr. Ananya,Orthopedic,NaN,Injury,NaN,paid,Mumbai
...,...,...,...,...,...,...,...,...,...,...,...,...
495,P496,David,Unknown,NaN,2023/11/06,Dr. Priya,Neurology,70.0,Injury,,paid,Delhi
496,P497,Rahul,NaN,Female,2023-02-11 0:00:00,Dr. David,Neurology,NaN,Diabetes,7730.47,UNPAID,Mumbai
497,P498,David,NaN,Male,07-02-2023,Dr. Ananya,NEURO,NaN,Injury,,Unpaid,Mumbai
498,P499,Sara,16,NaN,02-10-2023,Dr. Ananya,NEURO,108.0,Injury,NaN,paid,Delhi
499,P500,Rahul,Unknown,M,2023/10/10,Dr. Amit,Neurology,37.0,Diabetes,NaN,Paid,Bangalore

In [3]:
df_cpy1.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Patient_ID        469 non-null    str
 1   Name              500 non-null    str
 2   Age               347 non-null    str
 3   Gender            325 non-null    str
 4   Appointment_Date  500 non-null    str
 5   Doctor_Name       500 non-null    str
 6   Department        500 non-null    str
 7   Wait_Time(min)    172 non-null    float64
 8   Diagnosis         397 non-null    str
 9   Bill_Amount       334 non-null    str
 10  Payment_Status    500 non-null    str
 11  City              500 non-null    str
dtypes: float64(1), str(11)
memory usage: 47.0 KB

In [4]:
df_cpy1.isnull().sum()

Patient_ID           31
Name                  0
Age                 153
Gender              175
Appointment_Date      0
Doctor_Name           0
Department            0
Wait_Time(min)      328
Diagnosis           103
Bill_Amount         166
Payment_Status        0
City                  0
dtype: int64

In [5]:
#Remove records with Paitent ID = Null
df_cpy1.dropna(subset=['Patient_ID'])

,Patient_ID,Name,Age,Gender,Appointment_Date,Doctor_Name,Department,Wait_Time(min),Diagnosis,Bill_Amount,Payment_Status,City
0,P1,Priya,22,M,31-05-2023,Dr. Sara,Orthopedic,44.0,NaN,NaN,UNPAID,Bangalore
1,P2,David,Unknown,NaN,19-09-2023,Dr. Sara,Cardiology,58.0,Diabetes,6634.84,paid,Bangalore
2,P3,Rahul,13,M,2023-01-20 0:00:00,Dr. John,Cardiology,NaN,NaN,NaN,UNPAID,Kolkata
3,P4,Priya,Unknown,NaN,2023/04/13,Dr. Priya,Neurology,5.0,Checkup,NaN,Unpaid,Bangalore
4,P5,John,NaN,Male,2023/05/28,Dr. Ananya,Orthopedic,NaN,Injury,NaN,paid,Mumbai
...,...,...,...,...,...,...,...,...,...,...,...,...
495,P496,David,Unknown,NaN,2023/11/06,Dr. Priya,Neurology,70.0,Injury,,paid,Delhi
496,P497,Rahul,NaN,Female,2023-02-11 0:00:00,Dr. David,Neurology,NaN,Diabetes,7730.47,UNPAID,Mumbai
497,P498,David,NaN,Male,07-02-2023,Dr. Ananya,NEURO,NaN,Injury,,Unpaid,Mumbai
498,P499,Sara,16,NaN,02-10-2023,Dr. Ananya,NEURO,108.0,Injury,NaN,paid,Delhi
499,P500,Rahul,Unknown,M,2023/10/10,Dr. Amit,Neurology,37.0,Diabetes,NaN,Paid,Bangalore

In [7]:
# Convert Age to numeric
df_cpy1['Age'] = pd.to_numeric(df_cpy1['Age'],errors='coerce')

In [10]:
df_cpy1['Age'].dtype

dtype('float64')

In [11]:
# Fill the NaN values in age with the median value
df_cpy1['Age'] = df_cpy1['Age'].fillna(df_cpy1['Age'].median())
df_cpy1

,Patient_ID,Name,Age,Gender,Appointment_Date,Doctor_Name,Department,Wait_Time(min),Diagnosis,Bill_Amount,Payment_Status,City
0,P1,Priya,22.0,M,31-05-2023,Dr. Sara,Orthopedic,44.0,NaN,NaN,UNPAID,Bangalore
1,P2,David,45.0,NaN,19-09-2023,Dr. Sara,Cardiology,58.0,Diabetes,6634.84,paid,Bangalore
2,P3,Rahul,13.0,M,2023-01-20 0:00:00,Dr. John,Cardiology,NaN,NaN,NaN,UNPAID,Kolkata
3,P4,Priya,45.0,NaN,2023/04/13,Dr. Priya,Neurology,5.0,Checkup,NaN,Unpaid,Bangalore
4,P5,John,45.0,Male,2023/05/28,Dr. Ananya,Orthopedic,NaN,Injury,NaN,paid,Mumbai
...,...,...,...,...,...,...,...,...,...,...,...,...
495,P496,David,45.0,NaN,2023/11/06,Dr. Priya,Neurology,70.0,Injury,,paid,Delhi
496,P497,Rahul,45.0,Female,2023-02-11 0:00:00,Dr. David,Neurology,NaN,Diabetes,7730.47,UNPAID,Mumbai
497,P498,David,45.0,Male,07-02-2023,Dr. Ananya,NEURO,NaN,Injury,,Unpaid,Mumbai
498,P499,Sara,16.0,NaN,02-10-2023,Dr. Ananya,NEURO,108.0,Injury,NaN,paid,Delhi
499,P500,Rahul,45.0,M,2023/10/10,Dr. Amit,Neurology,37.0,Diabetes,NaN,Paid,Bangalore

In [12]:
#Wait_Time(min) -> numeric
df_cpy1['Wait_Time(min)'] = pd.to_numeric(df_cpy1['Wait_Time(min)'],errors='coerce')
df_cpy1

,Patient_ID,Name,Age,Gender,Appointment_Date,Doctor_Name,Department,Wait_Time(min),Diagnosis,Bill_Amount,Payment_Status,City
0,P1,Priya,22.0,M,31-05-2023,Dr. Sara,Orthopedic,44.0,NaN,NaN,UNPAID,Bangalore
1,P2,David,45.0,NaN,19-09-2023,Dr. Sara,Cardiology,58.0,Diabetes,6634.84,paid,Bangalore
2,P3,Rahul,13.0,M,2023-01-20 0:00:00,Dr. John,Cardiology,NaN,NaN,NaN,UNPAID,Kolkata
3,P4,Priya,45.0,NaN,2023/04/13,Dr. Priya,Neurology,5.0,Checkup,NaN,Unpaid,Bangalore
4,P5,John,45.0,Male,2023/05/28,Dr. Ananya,Orthopedic,NaN,Injury,NaN,paid,Mumbai
...,...,...,...,...,...,...,...,...,...,...,...,...
495,P496,David,45.0,NaN,2023/11/06,Dr. Priya,Neurology,70.0,Injury,,paid,Delhi
496,P497,Rahul,45.0,Female,2023-02-11 0:00:00,Dr. David,Neurology,NaN,Diabetes,7730.47,UNPAID,Mumbai
497,P498,David,45.0,Male,07-02-2023,Dr. Ananya,NEURO,NaN,Injury,,Unpaid,Mumbai
498,P499,Sara,16.0,NaN,02-10-2023,Dr. Ananya,NEURO,108.0,Injury,NaN,paid,Delhi
499,P500,Rahul,45.0,M,2023/10/10,Dr. Amit,Neurology,37.0,Diabetes,NaN,Paid,Bangalore

In [13]:
df_cpy1['Wait_Time(min)'].dtype

dtype('float64')

In [15]:
# fill the NaN with the mean waiting tim value
df_cpy1['Wait_Time(min)'] = df_cpy1['Wait_Time(min)'].fillna(round(df_cpy1['Wait_Time(min)'].mean(),2))
df_cpy1

,Patient_ID,Name,Age,Gender,Appointment_Date,Doctor_Name,Department,Wait_Time(min),Diagnosis,Bill_Amount,Payment_Status,City
0,P1,Priya,22.0,M,31-05-2023,Dr. Sara,Orthopedic,44.00000,NaN,NaN,UNPAID,Bangalore
1,P2,David,45.0,NaN,19-09-2023,Dr. Sara,Cardiology,58.00000,Diabetes,6634.84,paid,Bangalore
2,P3,Rahul,13.0,M,2023-01-20 0:00:00,Dr. John,Cardiology,60.55814,NaN,NaN,UNPAID,Kolkata
3,P4,Priya,45.0,NaN,2023/04/13,Dr. Priya,Neurology,5.00000,Checkup,NaN,Unpaid,Bangalore
4,P5,John,45.0,Male,2023/05/28,Dr. Ananya,Orthopedic,60.55814,Injury,NaN,paid,Mumbai
...,...,...,...,...,...,...,...,...,...,...,...,...
495,P496,David,45.0,NaN,2023/11/06,Dr. Priya,Neurology,70.00000,Injury,,paid,Delhi
496,P497,Rahul,45.0,Female,2023-02-11 0:00:00,Dr. David,Neurology,60.55814,Diabetes,7730.47,UNPAID,Mumbai
497,P498,David,45.0,Male,07-02-2023,Dr. Ananya,NEURO,60.55814,Injury,,Unpaid,Mumbai
498,P499,Sara,16.0,NaN,02-10-2023,Dr. Ananya,NEURO,108.00000,Injury,NaN,paid,Delhi
499,P500,Rahul,45.0,M,2023/10/10,Dr. Amit,Neurology,37.00000,Diabetes,NaN,Paid,Bangalore

In [16]:
# Name Cleaning
df_cpy1['Name'] = df_cpy1['Name'].str.strip().str.title()
df_cpy1

,Patient_ID,Name,Age,Gender,Appointment_Date,Doctor_Name,Department,Wait_Time(min),Diagnosis,Bill_Amount,Payment_Status,City
0,P1,Priya,22.0,M,31-05-2023,Dr. Sara,Orthopedic,44.00000,NaN,NaN,UNPAID,Bangalore
1,P2,David,45.0,NaN,19-09-2023,Dr. Sara,Cardiology,58.00000,Diabetes,6634.84,paid,Bangalore
2,P3,Rahul,13.0,M,2023-01-20 0:00:00,Dr. John,Cardiology,60.55814,NaN,NaN,UNPAID,Kolkata
3,P4,Priya,45.0,NaN,2023/04/13,Dr. Priya,Neurology,5.00000,Checkup,NaN,Unpaid,Bangalore
4,P5,John,45.0,Male,2023/05/28,Dr. Ananya,Orthopedic,60.55814,Injury,NaN,paid,Mumbai
...,...,...,...,...,...,...,...,...,...,...,...,...
495,P496,David,45.0,NaN,2023/11/06,Dr. Priya,Neurology,70.00000,Injury,,paid,Delhi
496,P497,Rahul,45.0,Female,2023-02-11 0:00:00,Dr. David,Neurology,60.55814,Diabetes,7730.47,UNPAID,Mumbai
497,P498,David,45.0,Male,07-02-2023,Dr. Ananya,NEURO,60.55814,Injury,,Unpaid,Mumbai
498,P499,Sara,16.0,NaN,02-10-2023,Dr. Ananya,NEURO,108.00000,Injury,NaN,paid,Delhi
499,P500,Rahul,45.0,M,2023/10/10,Dr. Amit,Neurology,37.00000,Diabetes,NaN,Paid,Bangalore

In [17]:
#Gender cleaning
df_cpy1['Gender'] = df_cpy1['Gender'].str.strip().str.lower()
df_cpy1

,Patient_ID,Name,Age,Gender,Appointment_Date,Doctor_Name,Department,Wait_Time(min),Diagnosis,Bill_Amount,Payment_Status,City
0,P1,Priya,22.0,m,31-05-2023,Dr. Sara,Orthopedic,44.00000,NaN,NaN,UNPAID,Bangalore
1,P2,David,45.0,NaN,19-09-2023,Dr. Sara,Cardiology,58.00000,Diabetes,6634.84,paid,Bangalore
2,P3,Rahul,13.0,m,2023-01-20 0:00:00,Dr. John,Cardiology,60.55814,NaN,NaN,UNPAID,Kolkata
3,P4,Priya,45.0,NaN,2023/04/13,Dr. Priya,Neurology,5.00000,Checkup,NaN,Unpaid,Bangalore
4,P5,John,45.0,male,2023/05/28,Dr. Ananya,Orthopedic,60.55814,Injury,NaN,paid,Mumbai
...,...,...,...,...,...,...,...,...,...,...,...,...
495,P496,David,45.0,NaN,2023/11/06,Dr. Priya,Neurology,70.00000,Injury,,paid,Delhi
496,P497,Rahul,45.0,female,2023-02-11 0:00:00,Dr. David,Neurology,60.55814,Diabetes,7730.47,UNPAID,Mumbai
497,P498,David,45.0,male,07-02-2023,Dr. Ananya,NEURO,60.55814,Injury,,Unpaid,Mumbai
498,P499,Sara,16.0,NaN,02-10-2023,Dr. Ananya,NEURO,108.00000,Injury,NaN,paid,Delhi
499,P500,Rahul,45.0,m,2023/10/10,Dr. Amit,Neurology,37.00000,Diabetes,NaN,Paid,Bangalore

In [20]:
df_cpy1['Gender'] = df_cpy1['Gender'].replace({
    'm':'Male',
    'male':'Male',
    'f':'Female',
    'female':'Female',
    'Maleale':'Male',
    'FemaleeMaleale':'Male'
})

df_cpy1

,Patient_ID,Name,Age,Gender,Appointment_Date,Doctor_Name,Department,Wait_Time(min),Diagnosis,Bill_Amount,Payment_Status,City
0,P1,Priya,22.0,Male,31-05-2023,Dr. Sara,Orthopedic,44.00000,NaN,NaN,UNPAID,Bangalore
1,P2,David,45.0,NaN,19-09-2023,Dr. Sara,Cardiology,58.00000,Diabetes,6634.84,paid,Bangalore
2,P3,Rahul,13.0,Male,2023-01-20 0:00:00,Dr. John,Cardiology,60.55814,NaN,NaN,UNPAID,Kolkata
3,P4,Priya,45.0,NaN,2023/04/13,Dr. Priya,Neurology,5.00000,Checkup,NaN,Unpaid,Bangalore
4,P5,John,45.0,Male,2023/05/28,Dr. Ananya,Orthopedic,60.55814,Injury,NaN,paid,Mumbai
...,...,...,...,...,...,...,...,...,...,...,...,...
495,P496,David,45.0,NaN,2023/11/06,Dr. Priya,Neurology,70.00000,Injury,,paid,Delhi
496,P497,Rahul,45.0,Male,2023-02-11 0:00:00,Dr. David,Neurology,60.55814,Diabetes,7730.47,UNPAID,Mumbai
497,P498,David,45.0,Male,07-02-2023,Dr. Ananya,NEURO,60.55814,Injury,,Unpaid,Mumbai
498,P499,Sara,16.0,NaN,02-10-2023,Dr. Ananya,NEURO,108.00000,Injury,NaN,paid,Delhi
499,P500,Rahul,45.0,Male,2023/10/10,Dr. Amit,Neurology,37.00000,Diabetes,NaN,Paid,Bangalore

In [23]:
#Department cleaning
df_cpy1['Department'].unique()

<StringArray>
['Orthopedic', 'Cardiology', 'Neurology', 'NEURO', 'cardiology ']
Length: 5, dtype: str

In [24]:
df_cpy1['Department'] = df_cpy1['Department'].str.strip().str.title()
df_cpy1

,Patient_ID,Name,Age,Gender,Appointment_Date,Doctor_Name,Department,Wait_Time(min),Diagnosis,Bill_Amount,Payment_Status,City
0,P1,Priya,22.0,Male,31-05-2023,Dr. Sara,Orthopedic,44.00000,NaN,NaN,UNPAID,Bangalore
1,P2,David,45.0,NaN,19-09-2023,Dr. Sara,Cardiology,58.00000,Diabetes,6634.84,paid,Bangalore
2,P3,Rahul,13.0,Male,2023-01-20 0:00:00,Dr. John,Cardiology,60.55814,NaN,NaN,UNPAID,Kolkata
3,P4,Priya,45.0,NaN,2023/04/13,Dr. Priya,Neurology,5.00000,Checkup,NaN,Unpaid,Bangalore
4,P5,John,45.0,Male,2023/05/28,Dr. Ananya,Orthopedic,60.55814,Injury,NaN,paid,Mumbai
...,...,...,...,...,...,...,...,...,...,...,...,...
495,P496,David,45.0,NaN,2023/11/06,Dr. Priya,Neurology,70.00000,Injury,,paid,Delhi
496,P497,Rahul,45.0,Male,2023-02-11 0:00:00,Dr. David,Neurology,60.55814,Diabetes,7730.47,UNPAID,Mumbai
497,P498,David,45.0,Male,07-02-2023,Dr. Ananya,Neuro,60.55814,Injury,,Unpaid,Mumbai
498,P499,Sara,16.0,NaN,02-10-2023,Dr. Ananya,Neuro,108.00000,Injury,NaN,paid,Delhi
499,P500,Rahul,45.0,Male,2023/10/10,Dr. Amit,Neurology,37.00000,Diabetes,NaN,Paid,Bangalore

In [25]:
df_cpy1['Department'] = df_cpy1['Department'].replace({
    'Neuro':'Neurology'
})

df_cpy1

,Patient_ID,Name,Age,Gender,Appointment_Date,Doctor_Name,Department,Wait_Time(min),Diagnosis,Bill_Amount,Payment_Status,City
0,P1,Priya,22.0,Male,31-05-2023,Dr. Sara,Orthopedic,44.00000,NaN,NaN,UNPAID,Bangalore
1,P2,David,45.0,NaN,19-09-2023,Dr. Sara,Cardiology,58.00000,Diabetes,6634.84,paid,Bangalore
2,P3,Rahul,13.0,Male,2023-01-20 0:00:00,Dr. John,Cardiology,60.55814,NaN,NaN,UNPAID,Kolkata
3,P4,Priya,45.0,NaN,2023/04/13,Dr. Priya,Neurology,5.00000,Checkup,NaN,Unpaid,Bangalore
4,P5,John,45.0,Male,2023/05/28,Dr. Ananya,Orthopedic,60.55814,Injury,NaN,paid,Mumbai
...,...,...,...,...,...,...,...,...,...,...,...,...
495,P496,David,45.0,NaN,2023/11/06,Dr. Priya,Neurology,70.00000,Injury,,paid,Delhi
496,P497,Rahul,45.0,Male,2023-02-11 0:00:00,Dr. David,Neurology,60.55814,Diabetes,7730.47,UNPAID,Mumbai
497,P498,David,45.0,Male,07-02-2023,Dr. Ananya,Neurology,60.55814,Injury,,Unpaid,Mumbai
498,P499,Sara,16.0,NaN,02-10-2023,Dr. Ananya,Neurology,108.00000,Injury,NaN,paid,Delhi
499,P500,Rahul,45.0,Male,2023/10/10,Dr. Amit,Neurology,37.00000,Diabetes,NaN,Paid,Bangalore

In [26]:
#City cleaning
df_cpy1['City'].unique()

<StringArray>
['Bangalore', 'Kolkata', 'Mumbai', 'kolkata', 'Delhi']
Length: 5, dtype: str

In [27]:
df_cpy1['City'] = df_cpy1['City'].str.strip().str.title()
df_cpy1

,Patient_ID,Name,Age,Gender,Appointment_Date,Doctor_Name,Department,Wait_Time(min),Diagnosis,Bill_Amount,Payment_Status,City
0,P1,Priya,22.0,Male,31-05-2023,Dr. Sara,Orthopedic,44.00000,NaN,NaN,UNPAID,Bangalore
1,P2,David,45.0,NaN,19-09-2023,Dr. Sara,Cardiology,58.00000,Diabetes,6634.84,paid,Bangalore
2,P3,Rahul,13.0,Male,2023-01-20 0:00:00,Dr. John,Cardiology,60.55814,NaN,NaN,UNPAID,Kolkata
3,P4,Priya,45.0,NaN,2023/04/13,Dr. Priya,Neurology,5.00000,Checkup,NaN,Unpaid,Bangalore
4,P5,John,45.0,Male,2023/05/28,Dr. Ananya,Orthopedic,60.55814,Injury,NaN,paid,Mumbai
...,...,...,...,...,...,...,...,...,...,...,...,...
495,P496,David,45.0,NaN,2023/11/06,Dr. Priya,Neurology,70.00000,Injury,,paid,Delhi
496,P497,Rahul,45.0,Male,2023-02-11 0:00:00,Dr. David,Neurology,60.55814,Diabetes,7730.47,UNPAID,Mumbai
497,P498,David,45.0,Male,07-02-2023,Dr. Ananya,Neurology,60.55814,Injury,,Unpaid,Mumbai
498,P499,Sara,16.0,NaN,02-10-2023,Dr. Ananya,Neurology,108.00000,Injury,NaN,paid,Delhi
499,P500,Rahul,45.0,Male,2023/10/10,Dr. Amit,Neurology,37.00000,Diabetes,NaN,Paid,Bangalore

In [28]:
df_cpy2 = df_cpy1.copy()
df_cpy2

,Patient_ID,Name,Age,Gender,Appointment_Date,Doctor_Name,Department,Wait_Time(min),Diagnosis,Bill_Amount,Payment_Status,City
0,P1,Priya,22.0,Male,31-05-2023,Dr. Sara,Orthopedic,44.00000,NaN,NaN,UNPAID,Bangalore
1,P2,David,45.0,NaN,19-09-2023,Dr. Sara,Cardiology,58.00000,Diabetes,6634.84,paid,Bangalore
2,P3,Rahul,13.0,Male,2023-01-20 0:00:00,Dr. John,Cardiology,60.55814,NaN,NaN,UNPAID,Kolkata
3,P4,Priya,45.0,NaN,2023/04/13,Dr. Priya,Neurology,5.00000,Checkup,NaN,Unpaid,Bangalore
4,P5,John,45.0,Male,2023/05/28,Dr. Ananya,Orthopedic,60.55814,Injury,NaN,paid,Mumbai
...,...,...,...,...,...,...,...,...,...,...,...,...
495,P496,David,45.0,NaN,2023/11/06,Dr. Priya,Neurology,70.00000,Injury,,paid,Delhi
496,P497,Rahul,45.0,Male,2023-02-11 0:00:00,Dr. David,Neurology,60.55814,Diabetes,7730.47,UNPAID,Mumbai
497,P498,David,45.0,Male,07-02-2023,Dr. Ananya,Neurology,60.55814,Injury,,Unpaid,Mumbai
498,P499,Sara,16.0,NaN,02-10-2023,Dr. Ananya,Neurology,108.00000,Injury,NaN,paid,Delhi
499,P500,Rahul,45.0,Male,2023/10/10,Dr. Amit,Neurology,37.00000,Diabetes,NaN,Paid,Bangalore

In [31]:
df_cpy2['Appointment_Date'] = pd.to_datetime(df_cpy2['Appointment_Date'],format='mixed',errors='coerce')
df_cpy2

,Patient_ID,Name,Age,Gender,Appointment_Date,Doctor_Name,Department,Wait_Time(min),Diagnosis,Bill_Amount,Payment_Status,City
0,P1,Priya,22.0,Male,2023-05-31,Dr. Sara,Orthopedic,44.00000,NaN,NaN,UNPAID,Bangalore
1,P2,David,45.0,NaN,2023-09-19,Dr. Sara,Cardiology,58.00000,Diabetes,6634.84,paid,Bangalore
2,P3,Rahul,13.0,Male,2023-01-20,Dr. John,Cardiology,60.55814,NaN,NaN,UNPAID,Kolkata
3,P4,Priya,45.0,NaN,2023-04-13,Dr. Priya,Neurology,5.00000,Checkup,NaN,Unpaid,Bangalore
4,P5,John,45.0,Male,2023-05-28,Dr. Ananya,Orthopedic,60.55814,Injury,NaN,paid,Mumbai
...,...,...,...,...,...,...,...,...,...,...,...,...
495,P496,David,45.0,NaN,2023-11-06,Dr. Priya,Neurology,70.00000,Injury,,paid,Delhi
496,P497,Rahul,45.0,Male,2023-02-11,Dr. David,Neurology,60.55814,Diabetes,7730.47,UNPAID,Mumbai
497,P498,David,45.0,Male,2023-07-02,Dr. Ananya,Neurology,60.55814,Injury,,Unpaid,Mumbai
498,P499,Sara,16.0,NaN,2023-02-10,Dr. Ananya,Neurology,108.00000,Injury,NaN,paid,Delhi
499,P500,Rahul,45.0,Male,2023-10-10,Dr. Amit,Neurology,37.00000,Diabetes,NaN,Paid,Bangalore

In [32]:
df_cpy2['Year'] = df_cpy2['Appointment_Date'].dt.year
df_cpy2['Month'] = df_cpy2['Appointment_Date'].dt.month
df_cpy2['Day'] = df_cpy2['Appointment_Date'].dt.day
df_cpy2['Weekday'] = df_cpy2['Appointment_Date'].dt.day_name()

df_cpy2

,Patient_ID,Name,Age,Gender,Appointment_Date,Doctor_Name,Department,Wait_Time(min),Diagnosis,Bill_Amount,Payment_Status,City,Year,Month,Day,Weekday
0,P1,Priya,22.0,Male,2023-05-31,Dr. Sara,Orthopedic,44.00000,NaN,NaN,UNPAID,Bangalore,2023,5,31,Wednesday
1,P2,David,45.0,NaN,2023-09-19,Dr. Sara,Cardiology,58.00000,Diabetes,6634.84,paid,Bangalore,2023,9,19,Tuesday
2,P3,Rahul,13.0,Male,2023-01-20,Dr. John,Cardiology,60.55814,NaN,NaN,UNPAID,Kolkata,2023,1,20,Friday
3,P4,Priya,45.0,NaN,2023-04-13,Dr. Priya,Neurology,5.00000,Checkup,NaN,Unpaid,Bangalore,2023,4,13,Thursday
4,P5,John,45.0,Male,2023-05-28,Dr. Ananya,Orthopedic,60.55814,Injury,NaN,paid,Mumbai,2023,5,28,Sunday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,P496,David,45.0,NaN,2023-11-06,Dr. Priya,Neurology,70.00000,Injury,,paid,Delhi,2023,11,6,Monday
496,P497,Rahul,45.0,Male,2023-02-11,Dr. David,Neurology,60.55814,Diabetes,7730.47,UNPAID,Mumbai,2023,2,11,Saturday
497,P498,David,45.0,Male,2023-07-02,Dr. Ananya,Neurology,60.55814,Injury,,Unpaid,Mumbai,2023,7,2,Sunday
498,P499,Sara,16.0,NaN,2023-02-10,Dr. Ananya,Neurology,108.00000,Injury,NaN,paid,Delhi,2023,2,10,Friday
499,P500,Rahul,45.0,Male,2023-10-10,Dr. Amit,Neurology,37.00000,Diabetes,NaN,Paid,Bangalore,2023,10,10,Tuesday

In [33]:
df_cpy2['Bill_Amount'].dtype

In [34]:
df_cpy2['Bill_Amount'] = pd.to_numeric(df_cpy2['Bill_Amount'],errors='coerce')
df_cpy2

,Patient_ID,Name,Age,Gender,Appointment_Date,Doctor_Name,Department,Wait_Time(min),Diagnosis,Bill_Amount,Payment_Status,City,Year,Month,Day,Weekday
0,P1,Priya,22.0,Male,2023-05-31,Dr. Sara,Orthopedic,44.00000,NaN,NaN,UNPAID,Bangalore,2023,5,31,Wednesday
1,P2,David,45.0,NaN,2023-09-19,Dr. Sara,Cardiology,58.00000,Diabetes,6634.84,paid,Bangalore,2023,9,19,Tuesday
2,P3,Rahul,13.0,Male,2023-01-20,Dr. John,Cardiology,60.55814,NaN,NaN,UNPAID,Kolkata,2023,1,20,Friday
3,P4,Priya,45.0,NaN,2023-04-13,Dr. Priya,Neurology,5.00000,Checkup,NaN,Unpaid,Bangalore,2023,4,13,Thursday
4,P5,John,45.0,Male,2023-05-28,Dr. Ananya,Orthopedic,60.55814,Injury,NaN,paid,Mumbai,2023,5,28,Sunday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,P496,David,45.0,NaN,2023-11-06,Dr. Priya,Neurology,70.00000,Injury,NaN,paid,Delhi,2023,11,6,Monday
496,P497,Rahul,45.0,Male,2023-02-11,Dr. David,Neurology,60.55814,Diabetes,7730.47,UNPAID,Mumbai,2023,2,11,Saturday
497,P498,David,45.0,Male,2023-07-02,Dr. Ananya,Neurology,60.55814,Injury,NaN,Unpaid,Mumbai,2023,7,2,Sunday
498,P499,Sara,16.0,NaN,2023-02-10,Dr. Ananya,Neurology,108.00000,Injury,NaN,paid,Delhi,2023,2,10,Friday
499,P500,Rahul,45.0,Male,2023-10-10,Dr. Amit,Neurology,37.00000,Diabetes,NaN,Paid,Bangalore,2023,10,10,Tuesday

In [35]:
df_cpy2['Bill_Amount'] = df_cpy2['Bill_Amount'].fillna(df_cpy2['Bill_Amount'].median())
df_cpy2

,Patient_ID,Name,Age,Gender,Appointment_Date,Doctor_Name,Department,Wait_Time(min),Diagnosis,Bill_Amount,Payment_Status,City,Year,Month,Day,Weekday
0,P1,Priya,22.0,Male,2023-05-31,Dr. Sara,Orthopedic,44.00000,NaN,4976.06,UNPAID,Bangalore,2023,5,31,Wednesday
1,P2,David,45.0,NaN,2023-09-19,Dr. Sara,Cardiology,58.00000,Diabetes,6634.84,paid,Bangalore,2023,9,19,Tuesday
2,P3,Rahul,13.0,Male,2023-01-20,Dr. John,Cardiology,60.55814,NaN,4976.06,UNPAID,Kolkata,2023,1,20,Friday
3,P4,Priya,45.0,NaN,2023-04-13,Dr. Priya,Neurology,5.00000,Checkup,4976.06,Unpaid,Bangalore,2023,4,13,Thursday
4,P5,John,45.0,Male,2023-05-28,Dr. Ananya,Orthopedic,60.55814,Injury,4976.06,paid,Mumbai,2023,5,28,Sunday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,P496,David,45.0,NaN,2023-11-06,Dr. Priya,Neurology,70.00000,Injury,4976.06,paid,Delhi,2023,11,6,Monday
496,P497,Rahul,45.0,Male,2023-02-11,Dr. David,Neurology,60.55814,Diabetes,7730.47,UNPAID,Mumbai,2023,2,11,Saturday
497,P498,David,45.0,Male,2023-07-02,Dr. Ananya,Neurology,60.55814,Injury,4976.06,Unpaid,Mumbai,2023,7,2,Sunday
498,P499,Sara,16.0,NaN,2023-02-10,Dr. Ananya,Neurology,108.00000,Injury,4976.06,paid,Delhi,2023,2,10,Friday
499,P500,Rahul,45.0,Male,2023-10-10,Dr. Amit,Neurology,37.00000,Diabetes,4976.06,Paid,Bangalore,2023,10,10,Tuesday

In [36]:
df_cpy2 = df_cpy2.drop_duplicates()
df_cpy2

,Patient_ID,Name,Age,Gender,Appointment_Date,Doctor_Name,Department,Wait_Time(min),Diagnosis,Bill_Amount,Payment_Status,City,Year,Month,Day,Weekday
0,P1,Priya,22.0,Male,2023-05-31,Dr. Sara,Orthopedic,44.00000,NaN,4976.06,UNPAID,Bangalore,2023,5,31,Wednesday
1,P2,David,45.0,NaN,2023-09-19,Dr. Sara,Cardiology,58.00000,Diabetes,6634.84,paid,Bangalore,2023,9,19,Tuesday
2,P3,Rahul,13.0,Male,2023-01-20,Dr. John,Cardiology,60.55814,NaN,4976.06,UNPAID,Kolkata,2023,1,20,Friday
3,P4,Priya,45.0,NaN,2023-04-13,Dr. Priya,Neurology,5.00000,Checkup,4976.06,Unpaid,Bangalore,2023,4,13,Thursday
4,P5,John,45.0,Male,2023-05-28,Dr. Ananya,Orthopedic,60.55814,Injury,4976.06,paid,Mumbai,2023,5,28,Sunday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,P496,David,45.0,NaN,2023-11-06,Dr. Priya,Neurology,70.00000,Injury,4976.06,paid,Delhi,2023,11,6,Monday
496,P497,Rahul,45.0,Male,2023-02-11,Dr. David,Neurology,60.55814,Diabetes,7730.47,UNPAID,Mumbai,2023,2,11,Saturday
497,P498,David,45.0,Male,2023-07-02,Dr. Ananya,Neurology,60.55814,Injury,4976.06,Unpaid,Mumbai,2023,7,2,Sunday
498,P499,Sara,16.0,NaN,2023-02-10,Dr. Ananya,Neurology,108.00000,Injury,4976.06,paid,Delhi,2023,2,10,Friday
499,P500,Rahul,45.0,Male,2023-10-10,Dr. Amit,Neurology,37.00000,Diabetes,4976.06,Paid,Bangalore,2023,10,10,Tuesday

In [40]:
df_cpy2['Payment_Status'] = df_cpy2['Payment_Status'].str.strip().str.title()
df_cpy2

,Patient_ID,Name,Age,Gender,Appointment_Date,Doctor_Name,Department,Wait_Time(min),Diagnosis,Bill_Amount,Payment_Status,City,Year,Month,Day,Weekday
0,P1,Priya,22.0,Male,2023-05-31,Dr. Sara,Orthopedic,44.00000,NaN,4976.06,Unpaid,Bangalore,2023,5,31,Wednesday
1,P2,David,45.0,NaN,2023-09-19,Dr. Sara,Cardiology,58.00000,Diabetes,6634.84,Paid,Bangalore,2023,9,19,Tuesday
2,P3,Rahul,13.0,Male,2023-01-20,Dr. John,Cardiology,60.55814,NaN,4976.06,Unpaid,Kolkata,2023,1,20,Friday
3,P4,Priya,45.0,NaN,2023-04-13,Dr. Priya,Neurology,5.00000,Checkup,4976.06,Unpaid,Bangalore,2023,4,13,Thursday
4,P5,John,45.0,Male,2023-05-28,Dr. Ananya,Orthopedic,60.55814,Injury,4976.06,Paid,Mumbai,2023,5,28,Sunday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,P496,David,45.0,NaN,2023-11-06,Dr. Priya,Neurology,70.00000,Injury,4976.06,Paid,Delhi,2023,11,6,Monday
496,P497,Rahul,45.0,Male,2023-02-11,Dr. David,Neurology,60.55814,Diabetes,7730.47,Unpaid,Mumbai,2023,2,11,Saturday
497,P498,David,45.0,Male,2023-07-02,Dr. Ananya,Neurology,60.55814,Injury,4976.06,Unpaid,Mumbai,2023,7,2,Sunday
498,P499,Sara,16.0,NaN,2023-02-10,Dr. Ananya,Neurology,108.00000,Injury,4976.06,Paid,Delhi,2023,2,10,Friday
499,P500,Rahul,45.0,Male,2023-10-10,Dr. Amit,Neurology,37.00000,Diabetes,4976.06,Paid,Bangalore,2023,10,10,Tuesday

## Feature Engineering ##

In [41]:
#Age Group
df_cpy3 = df_cpy2.copy()
df_cpy3

,Patient_ID,Name,Age,Gender,Appointment_Date,Doctor_Name,Department,Wait_Time(min),Diagnosis,Bill_Amount,Payment_Status,City,Year,Month,Day,Weekday
0,P1,Priya,22.0,Male,2023-05-31,Dr. Sara,Orthopedic,44.00000,NaN,4976.06,Unpaid,Bangalore,2023,5,31,Wednesday
1,P2,David,45.0,NaN,2023-09-19,Dr. Sara,Cardiology,58.00000,Diabetes,6634.84,Paid,Bangalore,2023,9,19,Tuesday
2,P3,Rahul,13.0,Male,2023-01-20,Dr. John,Cardiology,60.55814,NaN,4976.06,Unpaid,Kolkata,2023,1,20,Friday
3,P4,Priya,45.0,NaN,2023-04-13,Dr. Priya,Neurology,5.00000,Checkup,4976.06,Unpaid,Bangalore,2023,4,13,Thursday
4,P5,John,45.0,Male,2023-05-28,Dr. Ananya,Orthopedic,60.55814,Injury,4976.06,Paid,Mumbai,2023,5,28,Sunday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,P496,David,45.0,NaN,2023-11-06,Dr. Priya,Neurology,70.00000,Injury,4976.06,Paid,Delhi,2023,11,6,Monday
496,P497,Rahul,45.0,Male,2023-02-11,Dr. David,Neurology,60.55814,Diabetes,7730.47,Unpaid,Mumbai,2023,2,11,Saturday
497,P498,David,45.0,Male,2023-07-02,Dr. Ananya,Neurology,60.55814,Injury,4976.06,Unpaid,Mumbai,2023,7,2,Sunday
498,P499,Sara,16.0,NaN,2023-02-10,Dr. Ananya,Neurology,108.00000,Injury,4976.06,Paid,Delhi,2023,2,10,Friday
499,P500,Rahul,45.0,Male,2023-10-10,Dr. Amit,Neurology,37.00000,Diabetes,4976.06,Paid,Bangalore,2023,10,10,Tuesday

In [42]:
# Age Group
df_cpy3['Age_Group'] = pd.cut(df_cpy3['Age'],bins=[0,18,35,60,100],labels=['Child','Young','Adult','Senior'])
df_cpy3

,Patient_ID,Name,Age,Gender,Appointment_Date,Doctor_Name,Department,Wait_Time(min),Diagnosis,Bill_Amount,Payment_Status,City,Year,Month,Day,Weekday,Age_Group
0,P1,Priya,22.0,Male,2023-05-31,Dr. Sara,Orthopedic,44.00000,NaN,4976.06,Unpaid,Bangalore,2023,5,31,Wednesday,Young
1,P2,David,45.0,NaN,2023-09-19,Dr. Sara,Cardiology,58.00000,Diabetes,6634.84,Paid,Bangalore,2023,9,19,Tuesday,Adult
2,P3,Rahul,13.0,Male,2023-01-20,Dr. John,Cardiology,60.55814,NaN,4976.06,Unpaid,Kolkata,2023,1,20,Friday,Child
3,P4,Priya,45.0,NaN,2023-04-13,Dr. Priya,Neurology,5.00000,Checkup,4976.06,Unpaid,Bangalore,2023,4,13,Thursday,Adult
4,P5,John,45.0,Male,2023-05-28,Dr. Ananya,Orthopedic,60.55814,Injury,4976.06,Paid,Mumbai,2023,5,28,Sunday,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,P496,David,45.0,NaN,2023-11-06,Dr. Priya,Neurology,70.00000,Injury,4976.06,Paid,Delhi,2023,11,6,Monday,Adult
496,P497,Rahul,45.0,Male,2023-02-11,Dr. David,Neurology,60.55814,Diabetes,7730.47,Unpaid,Mumbai,2023,2,11,Saturday,Adult
497,P498,David,45.0,Male,2023-07-02,Dr. Ananya,Neurology,60.55814,Injury,4976.06,Unpaid,Mumbai,2023,7,2,Sunday,Adult
498,P499,Sara,16.0,NaN,2023-02-10,Dr. Ananya,Neurology,108.00000,Injury,4976.06,Paid,Delhi,2023,2,10,Friday,Child
499,P500,Rahul,45.0,Male,2023-10-10,Dr. Amit,Neurology,37.00000,Diabetes,4976.06,Paid,Bangalore,2023,10,10,Tuesday,Adult

In [43]:
#High bill
df_cpy3['High_Bill']=df_cpy3['Bill_Amount']>5000
df_cpy3

,Patient_ID,Name,Age,Gender,Appointment_Date,Doctor_Name,Department,Wait_Time(min),Diagnosis,Bill_Amount,Payment_Status,City,Year,Month,Day,Weekday,Age_Group,High_Bill
0,P1,Priya,22.0,Male,2023-05-31,Dr. Sara,Orthopedic,44.00000,NaN,4976.06,Unpaid,Bangalore,2023,5,31,Wednesday,Young,False
1,P2,David,45.0,NaN,2023-09-19,Dr. Sara,Cardiology,58.00000,Diabetes,6634.84,Paid,Bangalore,2023,9,19,Tuesday,Adult,True
2,P3,Rahul,13.0,Male,2023-01-20,Dr. John,Cardiology,60.55814,NaN,4976.06,Unpaid,Kolkata,2023,1,20,Friday,Child,False
3,P4,Priya,45.0,NaN,2023-04-13,Dr. Priya,Neurology,5.00000,Checkup,4976.06,Unpaid,Bangalore,2023,4,13,Thursday,Adult,False
4,P5,John,45.0,Male,2023-05-28,Dr. Ananya,Orthopedic,60.55814,Injury,4976.06,Paid,Mumbai,2023,5,28,Sunday,Adult,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,P496,David,45.0,NaN,2023-11-06,Dr. Priya,Neurology,70.00000,Injury,4976.06,Paid,Delhi,2023,11,6,Monday,Adult,False
496,P497,Rahul,45.0,Male,2023-02-11,Dr. David,Neurology,60.55814,Diabetes,7730.47,Unpaid,Mumbai,2023,2,11,Saturday,Adult,True
497,P498,David,45.0,Male,2023-07-02,Dr. Ananya,Neurology,60.55814,Injury,4976.06,Unpaid,Mumbai,2023,7,2,Sunday,Adult,False
498,P499,Sara,16.0,NaN,2023-02-10,Dr. Ananya,Neurology,108.00000,Injury,4976.06,Paid,Delhi,2023,2,10,Friday,Child,False
499,P500,Rahul,45.0,Male,2023-10-10,Dr. Amit,Neurology,37.00000,Diabetes,4976.06,Paid,Bangalore,2023,10,10,Tuesday,Adult,False

In [44]:
# long waiting
df_cpy3['Long_Wait'] = df_cpy3['Wait_Time(min)'] > 60
df_cpy3

,Patient_ID,Name,Age,Gender,Appointment_Date,Doctor_Name,Department,Wait_Time(min),Diagnosis,Bill_Amount,Payment_Status,City,Year,Month,Day,Weekday,Age_Group,High_Bill,Long_Wait
0,P1,Priya,22.0,Male,2023-05-31,Dr. Sara,Orthopedic,44.00000,NaN,4976.06,Unpaid,Bangalore,2023,5,31,Wednesday,Young,False,False
1,P2,David,45.0,NaN,2023-09-19,Dr. Sara,Cardiology,58.00000,Diabetes,6634.84,Paid,Bangalore,2023,9,19,Tuesday,Adult,True,False
2,P3,Rahul,13.0,Male,2023-01-20,Dr. John,Cardiology,60.55814,NaN,4976.06,Unpaid,Kolkata,2023,1,20,Friday,Child,False,True
3,P4,Priya,45.0,NaN,2023-04-13,Dr. Priya,Neurology,5.00000,Checkup,4976.06,Unpaid,Bangalore,2023,4,13,Thursday,Adult,False,False
4,P5,John,45.0,Male,2023-05-28,Dr. Ananya,Orthopedic,60.55814,Injury,4976.06,Paid,Mumbai,2023,5,28,Sunday,Adult,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,P496,David,45.0,NaN,2023-11-06,Dr. Priya,Neurology,70.00000,Injury,4976.06,Paid,Delhi,2023,11,6,Monday,Adult,False,True
496,P497,Rahul,45.0,Male,2023-02-11,Dr. David,Neurology,60.55814,Diabetes,7730.47,Unpaid,Mumbai,2023,2,11,Saturday,Adult,True,True
497,P498,David,45.0,Male,2023-07-02,Dr. Ananya,Neurology,60.55814,Injury,4976.06,Unpaid,Mumbai,2023,7,2,Sunday,Adult,False,True
498,P499,Sara,16.0,NaN,2023-02-10,Dr. Ananya,Neurology,108.00000,Injury,4976.06,Paid,Delhi,2023,2,10,Friday,Child,False,True
499,P500,Rahul,45.0,Male,2023-10-10,Dr. Amit,Neurology,37.00000,Diabetes,4976.06,Paid,Bangalore,2023,10,10,Tuesday,Adult,False,False

In [45]:
df_cpy3

,Patient_ID,Name,Age,Gender,Appointment_Date,Doctor_Name,Department,Wait_Time(min),Diagnosis,Bill_Amount,Payment_Status,City,Year,Month,Day,Weekday,Age_Group,High_Bill,Long_Wait
0,P1,Priya,22.0,Male,2023-05-31,Dr. Sara,Orthopedic,44.00000,NaN,4976.06,Unpaid,Bangalore,2023,5,31,Wednesday,Young,False,False
1,P2,David,45.0,NaN,2023-09-19,Dr. Sara,Cardiology,58.00000,Diabetes,6634.84,Paid,Bangalore,2023,9,19,Tuesday,Adult,True,False
2,P3,Rahul,13.0,Male,2023-01-20,Dr. John,Cardiology,60.55814,NaN,4976.06,Unpaid,Kolkata,2023,1,20,Friday,Child,False,True
3,P4,Priya,45.0,NaN,2023-04-13,Dr. Priya,Neurology,5.00000,Checkup,4976.06,Unpaid,Bangalore,2023,4,13,Thursday,Adult,False,False
4,P5,John,45.0,Male,2023-05-28,Dr. Ananya,Orthopedic,60.55814,Injury,4976.06,Paid,Mumbai,2023,5,28,Sunday,Adult,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,P496,David,45.0,NaN,2023-11-06,Dr. Priya,Neurology,70.00000,Injury,4976.06,Paid,Delhi,2023,11,6,Monday,Adult,False,True
496,P497,Rahul,45.0,Male,2023-02-11,Dr. David,Neurology,60.55814,Diabetes,7730.47,Unpaid,Mumbai,2023,2,11,Saturday,Adult,True,True
497,P498,David,45.0,Male,2023-07-02,Dr. Ananya,Neurology,60.55814,Injury,4976.06,Unpaid,Mumbai,2023,7,2,Sunday,Adult,False,True
498,P499,Sara,16.0,NaN,2023-02-10,Dr. Ananya,Neurology,108.00000,Injury,4976.06,Paid,Delhi,2023,2,10,Friday,Child,False,True
499,P500,Rahul,45.0,Male,2023-10-10,Dr. Amit,Neurology,37.00000,Diabetes,4976.06,Paid,Bangalore,2023,10,10,Tuesday,Adult,False,False

In [46]:
df_cpy3.isnull().sum()

Patient_ID           31
Name                  0
Age                   0
Gender              175
Appointment_Date      0
Doctor_Name           0
Department            0
Wait_Time(min)        0
Diagnosis           103
Bill_Amount           0
Payment_Status        0
City                  0
Year                  0
Month                 0
Day                   0
Weekday               0
Age_Group             0
High_Bill             0
Long_Wait             0
dtype: int64

In [47]:
df_cpy3.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Patient_ID        469 non-null    str
 1   Name              500 non-null    str
 2   Age               500 non-null    float64
 3   Gender            325 non-null    str
 4   Appointment_Date  500 non-null    datetime64[us]
 5   Doctor_Name       500 non-null    str
 6   Department        500 non-null    str
 7   Wait_Time(min)    500 non-null    float64
 8   Diagnosis         397 non-null    str
 9   Bill_Amount       500 non-null    float64
 10  Payment_Status    500 non-null    str
 11  City              500 non-null    str
 12  Year              500 non-null    int32
 13  Month             500 non-null    int32
 14  Day               500 non-null    int32
 15  Weekday           500 non-null    str
 16  Age_Group         500 non-null    category
 17  High_Bill         500 non-null    bool
 18  Long_Wait         500 non-null    bool
dtypes: bool(2), category(1), datetime64[us](1), float64(3), int32(3), str(9)
memory usage: 58.4 KB

In [48]:
df_cpy3.to_csv('Cleaned_HealthCare_Data.csv', index=False)